version: '3.8'

services:
  azure-function-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7071:80"
      - "2222:2222"
    environment:
      AzureWebJobsScriptRoot: /home/site/wwwroot
      AzureFunctionsJobHost__Logging__Console__IsEnabled: true
      WEBSITES_INCLUDE_CLOUD_CERTS: true
      AZURE_FUNCTIONS_ENVIRONMENT: Development
    volumes:
      - .:/home/site/wwwroot
